[project]
name = "big_data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "justinreal", email = "justin.real@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
big_data = "uv_work:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
